### ISSUE TITLE
So far, the supported features are incomplete.

### ISSUE THREAD

**Issue by sbfkcel** [microsoft/node-speech#33]
Can you provide the complete C++ API binding?

For example: streams, audio files...

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/cpp/embedded-speech

**Comment by bpasero** [comment]
Sorry but the plan is not to provide a complete binding, rather we only support what https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech needs.
